/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as FilesRouteImport } from './routes/files'
import { Route as GithubRouteImport } from './routes/github'
import { Route as InfoRouteImport } from './routes/info'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TwitterRouteImport } from './routes/twitter'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as XRouteImport } from './routes/x'
import { Route as AppSplatRouteImport } from './routes/_app.$'
import { Route as AppAccessRouteImport } from './routes/_app.access'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppBackupsRouteImport } from './routes/_app.backups'
import { Route as AppInfraRouteImport } from './routes/_app.infra'
import { Route as AppOperationsRouteImport } from './routes/_app.operations'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiRealtimeRouteImport } from './routes/api.realtime'
import { Route as ApiSentryCheckRouteImport } from './routes/api.sentry-check'
import { Route as CliAuthorizeRouteImport } from './routes/cli.authorize'
import { Route as DownloadsIdRouteImport } from './routes/downloads.$id'
import { Route as AppAutomationsIndexRouteImport } from './routes/_app.automations.index'
import { Route as AppAutomationsCalendarRouteImport } from './routes/_app.automations.calendar'
import { Route as AppAutomationsHistoryRouteImport } from './routes/_app.automations.history'
import { Route as AppAutomationsSchedulesRouteImport } from './routes/_app.automations.schedules'
import { Route as AppAutomationsSyncRouteImport } from './routes/_app.automations.sync'
import { Route as AppBackupsIndexRouteImport } from './routes/_app.backups.index'
import { Route as AppBackupsDestinationsRouteImport } from './routes/_app.backups.destinations'
import { Route as AppBackupsRunsRouteImport } from './routes/_app.backups.runs'
import { Route as AppBackupsSettingsRouteImport } from './routes/_app.backups.settings'
import { Route as AppInfraIndexRouteImport } from './routes/_app.infra.index'
import { Route as AppInfraDatabasesRouteImport } from './routes/_app.infra.databases'
import { Route as AppInfraDomainsRouteImport } from './routes/_app.infra.domains'
import { Route as AppInfraRelaysRouteImport } from './routes/_app.infra.relays'
import { Route as AppInfraServersRouteImport } from './routes/_app.infra.servers'
import { Route as AppInfraSetupRouteImport } from './routes/_app.infra.setup'
import { Route as AppInfraTailscaleRouteImport } from './routes/_app.infra.tailscale'
import { Route as AppServerServerIdRouteImport } from './routes/_app/server/$serverId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app.settings.account'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings.appearance'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppSettingsFilesRouteImport } from './routes/_app.settings.files'
import { Route as AppSettingsRelaysRouteImport } from './routes/_app.settings.relays'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiConsoleInstanceIdRouteImport } from './routes/api.console.$instanceId'
import { Route as AppServerServerIdIndexRouteImport } from './routes/_app/server/$serverId.index'
import { Route as AppServerServerIdSplatRouteImport } from './routes/_app/server/$serverId.$'
import { Route as AppServerServerIdConsoleRouteImport } from './routes/_app/server/$serverId.console'
import { Route as AppServerServerIdFilesRouteImport } from './routes/_app/server/$serverId.files'
import { Route as AppServerServerIdInfoRouteImport } from './routes/_app/server/$serverId.info'
import { Route as AppServerServerIdNetworkRouteImport } from './routes/_app/server/$serverId.network'
import { Route as AppServerServerIdStartupRouteImport } from './routes/_app/server/$serverId.startup'
import { Route as ApiCliAuthDeviceRouteImport } from './routes/api.cli.auth.device'
import { Route as ApiCliAuthTokenRouteImport } from './routes/api.cli.auth.token'
import { Route as ApiCliV1SplatRouteImport } from './routes/api.cli.v1.$'
import { Route as AppServerServerIdFilesSplatRouteImport } from './routes/_app/server/$serverId.files.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitterRoute = TwitterRouteImport.update({
  id: '/twitter',
  path: '/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsRoute = AppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppRoute,
} as any)
const AppInfraRoute = AppInfraRouteImport.update({
  id: '/infra',
  path: '/infra',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsRoute = AppOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryCheckRoute = ApiSentryCheckRouteImport.update({
  id: '/api/sentry-check',
  path: '/api/sentry-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthorizeRoute = CliAuthorizeRouteImport.update({
  id: '/cli/authorize',
  path: '/cli/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIdRoute = DownloadsIdRouteImport.update({
  id: '/downloads/$id',
  path: '/downloads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutomationsIndexRoute = AppAutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAutomationsRoute,
} as any)
const AppAutomationsCalendarRoute = AppAutomationsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppAutomationsRoute,
} as any)
const AppAutomationsHistoryRoute = AppAutomationsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppAutomationsRoute,
} as any)
const AppAutomationsSchedulesRoute = AppAutomationsSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppAutomationsRoute,
} as any)
const AppAutomationsSyncRoute = AppAutomationsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppAutomationsRoute,
} as any)
const AppBackupsIndexRoute = AppBackupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBackupsRoute,
} as any)
const AppBackupsDestinationsRoute = AppBackupsDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AppBackupsRoute,
} as any)
const AppBackupsRunsRoute = AppBackupsRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppBackupsRoute,
} as any)
const AppBackupsSettingsRoute = AppBackupsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppBackupsRoute,
} as any)
const AppInfraIndexRoute = AppInfraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInfraRoute,
} as any)
const AppInfraDatabasesRoute = AppInfraDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AppInfraRoute,
} as any)
const AppInfraDomainsRoute = AppInfraDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppInfraRoute,
} as any)
const AppInfraRelaysRoute = AppInfraRelaysRouteImport.update({
  id: '/relays',
  path: '/relays',
  getParentRoute: () => AppInfraRoute,
} as any)
const AppInfraServersRoute = AppInfraServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppInfraRoute,
} as any)
const AppInfraSetupRoute = AppInfraSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppInfraRoute,
} as any)
const AppInfraTailscaleRoute = AppInfraTailscaleRouteImport.update({
  id: '/tailscale',
  path: '/tailscale',
  getParentRoute: () => AppInfraRoute,
} as any)
const AppServerServerIdRoute = AppServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsFilesRoute = AppSettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsRelaysRoute = AppSettingsRelaysRouteImport.update({
  id: '/relays',
  path: '/relays',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleInstanceIdRoute = ApiConsoleInstanceIdRouteImport.update({
  id: '/api/console/$instanceId',
  path: '/api/console/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServerServerIdIndexRoute = AppServerServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServerServerIdRoute,
} as any)
const AppServerServerIdSplatRoute = AppServerServerIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppServerServerIdRoute,
} as any)
const AppServerServerIdConsoleRoute =
  AppServerServerIdConsoleRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => AppServerServerIdRoute,
  } as any)
const AppServerServerIdFilesRoute = AppServerServerIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppServerServerIdRoute,
} as any)
const AppServerServerIdInfoRoute = AppServerServerIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AppServerServerIdRoute,
} as any)
const AppServerServerIdNetworkRoute =
  AppServerServerIdNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AppServerServerIdRoute,
  } as any)
const AppServerServerIdStartupRoute =
  AppServerServerIdStartupRouteImport.update({
    id: '/startup',
    path: '/startup',
    getParentRoute: () => AppServerServerIdRoute,
  } as any)
const ApiCliAuthDeviceRoute = ApiCliAuthDeviceRouteImport.update({
  id: '/api/cli/auth/device',
  path: '/api/cli/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAuthTokenRoute = ApiCliAuthTokenRouteImport.update({
  id: '/api/cli/auth/token',
  path: '/api/cli/auth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliV1SplatRoute = ApiCliV1SplatRouteImport.update({
  id: '/api/cli/v1/$',
  path: '/api/cli/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServerServerIdFilesSplatRoute =
  AppServerServerIdFilesSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AppServerServerIdFilesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/discord': typeof DiscordRoute
  '/files': typeof FilesRoute
  '/github': typeof GithubRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/twitter': typeof TwitterRoute
  '/two-factor': typeof TwoFactorRoute
  '/x': typeof XRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/activity': typeof AppActivityRoute
  '/automations': typeof AppAutomationsRouteWithChildren
  '/backups': typeof AppBackupsRouteWithChildren
  '/infra': typeof AppInfraRouteWithChildren
  '/operations': typeof AppOperationsRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/downloads/$id': typeof DownloadsIdRoute
  '/automations/calendar': typeof AppAutomationsCalendarRoute
  '/automations/history': typeof AppAutomationsHistoryRoute
  '/automations/schedules': typeof AppAutomationsSchedulesRoute
  '/automations/sync': typeof AppAutomationsSyncRoute
  '/backups/destinations': typeof AppBackupsDestinationsRoute
  '/backups/runs': typeof AppBackupsRunsRoute
  '/backups/settings': typeof AppBackupsSettingsRoute
  '/infra/databases': typeof AppInfraDatabasesRoute
  '/infra/domains': typeof AppInfraDomainsRoute
  '/infra/relays': typeof AppInfraRelaysRoute
  '/infra/servers': typeof AppInfraServersRoute
  '/infra/setup': typeof AppInfraSetupRoute
  '/infra/tailscale': typeof AppInfraTailscaleRoute
  '/server/$serverId': typeof AppServerServerIdRouteWithChildren
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/files': typeof AppSettingsFilesRoute
  '/settings/relays': typeof AppSettingsRelaysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/automations/': typeof AppAutomationsIndexRoute
  '/backups/': typeof AppBackupsIndexRoute
  '/infra/': typeof AppInfraIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/server/$serverId/$': typeof AppServerServerIdSplatRoute
  '/server/$serverId/console': typeof AppServerServerIdConsoleRoute
  '/server/$serverId/files': typeof AppServerServerIdFilesRouteWithChildren
  '/server/$serverId/info': typeof AppServerServerIdInfoRoute
  '/server/$serverId/network': typeof AppServerServerIdNetworkRoute
  '/server/$serverId/startup': typeof AppServerServerIdStartupRoute
  '/api/cli/auth/device': typeof ApiCliAuthDeviceRoute
  '/api/cli/auth/token': typeof ApiCliAuthTokenRoute
  '/api/cli/v1/$': typeof ApiCliV1SplatRoute
  '/server/$serverId/': typeof AppServerServerIdIndexRoute
  '/server/$serverId/files/$': typeof AppServerServerIdFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/discord': typeof DiscordRoute
  '/files': typeof FilesRoute
  '/github': typeof GithubRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/twitter': typeof TwitterRoute
  '/two-factor': typeof TwoFactorRoute
  '/x': typeof XRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/activity': typeof AppActivityRoute
  '/operations': typeof AppOperationsRoute
  '/servers': typeof AppServersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/downloads/$id': typeof DownloadsIdRoute
  '/automations/calendar': typeof AppAutomationsCalendarRoute
  '/automations/history': typeof AppAutomationsHistoryRoute
  '/automations/schedules': typeof AppAutomationsSchedulesRoute
  '/automations/sync': typeof AppAutomationsSyncRoute
  '/backups/destinations': typeof AppBackupsDestinationsRoute
  '/backups/runs': typeof AppBackupsRunsRoute
  '/backups/settings': typeof AppBackupsSettingsRoute
  '/infra/databases': typeof AppInfraDatabasesRoute
  '/infra/domains': typeof AppInfraDomainsRoute
  '/infra/relays': typeof AppInfraRelaysRoute
  '/infra/servers': typeof AppInfraServersRoute
  '/infra/setup': typeof AppInfraSetupRoute
  '/infra/tailscale': typeof AppInfraTailscaleRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/files': typeof AppSettingsFilesRoute
  '/settings/relays': typeof AppSettingsRelaysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/automations': typeof AppAutomationsIndexRoute
  '/backups': typeof AppBackupsIndexRoute
  '/infra': typeof AppInfraIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/server/$serverId/$': typeof AppServerServerIdSplatRoute
  '/server/$serverId/console': typeof AppServerServerIdConsoleRoute
  '/server/$serverId/files': typeof AppServerServerIdFilesRouteWithChildren
  '/server/$serverId/info': typeof AppServerServerIdInfoRoute
  '/server/$serverId/network': typeof AppServerServerIdNetworkRoute
  '/server/$serverId/startup': typeof AppServerServerIdStartupRoute
  '/api/cli/auth/device': typeof ApiCliAuthDeviceRoute
  '/api/cli/auth/token': typeof ApiCliAuthTokenRoute
  '/api/cli/v1/$': typeof ApiCliV1SplatRoute
  '/server/$serverId': typeof AppServerServerIdIndexRoute
  '/server/$serverId/files/$': typeof AppServerServerIdFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/console': typeof ConsoleRoute
  '/discord': typeof DiscordRoute
  '/files': typeof FilesRoute
  '/github': typeof GithubRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/twitter': typeof TwitterRoute
  '/two-factor': typeof TwoFactorRoute
  '/x': typeof XRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/automations': typeof AppAutomationsRouteWithChildren
  '/_app/backups': typeof AppBackupsRouteWithChildren
  '/_app/infra': typeof AppInfraRouteWithChildren
  '/_app/operations': typeof AppOperationsRoute
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/downloads/$id': typeof DownloadsIdRoute
  '/_app/automations/calendar': typeof AppAutomationsCalendarRoute
  '/_app/automations/history': typeof AppAutomationsHistoryRoute
  '/_app/automations/schedules': typeof AppAutomationsSchedulesRoute
  '/_app/automations/sync': typeof AppAutomationsSyncRoute
  '/_app/backups/destinations': typeof AppBackupsDestinationsRoute
  '/_app/backups/runs': typeof AppBackupsRunsRoute
  '/_app/backups/settings': typeof AppBackupsSettingsRoute
  '/_app/infra/databases': typeof AppInfraDatabasesRoute
  '/_app/infra/domains': typeof AppInfraDomainsRoute
  '/_app/infra/relays': typeof AppInfraRelaysRoute
  '/_app/infra/servers': typeof AppInfraServersRoute
  '/_app/infra/setup': typeof AppInfraSetupRoute
  '/_app/infra/tailscale': typeof AppInfraTailscaleRoute
  '/_app/server/$serverId': typeof AppServerServerIdRouteWithChildren
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/files': typeof AppSettingsFilesRoute
  '/_app/settings/relays': typeof AppSettingsRelaysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/_app/automations/': typeof AppAutomationsIndexRoute
  '/_app/backups/': typeof AppBackupsIndexRoute
  '/_app/infra/': typeof AppInfraIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/server/$serverId/$': typeof AppServerServerIdSplatRoute
  '/_app/server/$serverId/console': typeof AppServerServerIdConsoleRoute
  '/_app/server/$serverId/files': typeof AppServerServerIdFilesRouteWithChildren
  '/_app/server/$serverId/info': typeof AppServerServerIdInfoRoute
  '/_app/server/$serverId/network': typeof AppServerServerIdNetworkRoute
  '/_app/server/$serverId/startup': typeof AppServerServerIdStartupRoute
  '/api/cli/auth/device': typeof ApiCliAuthDeviceRoute
  '/api/cli/auth/token': typeof ApiCliAuthTokenRoute
  '/api/cli/v1/$': typeof ApiCliV1SplatRoute
  '/_app/server/$serverId/': typeof AppServerServerIdIndexRoute
  '/_app/server/$serverId/files/$': typeof AppServerServerIdFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/discord'
    | '/files'
    | '/github'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/twitter'
    | '/two-factor'
    | '/x'
    | '/$'
    | '/access'
    | '/activity'
    | '/automations'
    | '/backups'
    | '/infra'
    | '/operations'
    | '/servers'
    | '/settings'
    | '/api/health'
    | '/api/realtime'
    | '/api/sentry-check'
    | '/cli/authorize'
    | '/downloads/$id'
    | '/automations/calendar'
    | '/automations/history'
    | '/automations/schedules'
    | '/automations/sync'
    | '/backups/destinations'
    | '/backups/runs'
    | '/backups/settings'
    | '/infra/databases'
    | '/infra/domains'
    | '/infra/relays'
    | '/infra/servers'
    | '/infra/setup'
    | '/infra/tailscale'
    | '/server/$serverId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/relays'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/automations/'
    | '/backups/'
    | '/infra/'
    | '/settings/'
    | '/server/$serverId/$'
    | '/server/$serverId/console'
    | '/server/$serverId/files'
    | '/server/$serverId/info'
    | '/server/$serverId/network'
    | '/server/$serverId/startup'
    | '/api/cli/auth/device'
    | '/api/cli/auth/token'
    | '/api/cli/v1/$'
    | '/server/$serverId/'
    | '/server/$serverId/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/discord'
    | '/files'
    | '/github'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/twitter'
    | '/two-factor'
    | '/x'
    | '/$'
    | '/access'
    | '/activity'
    | '/operations'
    | '/servers'
    | '/api/health'
    | '/api/realtime'
    | '/api/sentry-check'
    | '/cli/authorize'
    | '/downloads/$id'
    | '/automations/calendar'
    | '/automations/history'
    | '/automations/schedules'
    | '/automations/sync'
    | '/backups/destinations'
    | '/backups/runs'
    | '/backups/settings'
    | '/infra/databases'
    | '/infra/domains'
    | '/infra/relays'
    | '/infra/servers'
    | '/infra/setup'
    | '/infra/tailscale'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/relays'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/automations'
    | '/backups'
    | '/infra'
    | '/settings'
    | '/server/$serverId/$'
    | '/server/$serverId/console'
    | '/server/$serverId/files'
    | '/server/$serverId/info'
    | '/server/$serverId/network'
    | '/server/$serverId/startup'
    | '/api/cli/auth/device'
    | '/api/cli/auth/token'
    | '/api/cli/v1/$'
    | '/server/$serverId'
    | '/server/$serverId/files/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/console'
    | '/discord'
    | '/files'
    | '/github'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/twitter'
    | '/two-factor'
    | '/x'
    | '/_app/$'
    | '/_app/access'
    | '/_app/activity'
    | '/_app/automations'
    | '/_app/backups'
    | '/_app/infra'
    | '/_app/operations'
    | '/_app/servers'
    | '/_app/settings'
    | '/api/health'
    | '/api/realtime'
    | '/api/sentry-check'
    | '/cli/authorize'
    | '/downloads/$id'
    | '/_app/automations/calendar'
    | '/_app/automations/history'
    | '/_app/automations/schedules'
    | '/_app/automations/sync'
    | '/_app/backups/destinations'
    | '/_app/backups/runs'
    | '/_app/backups/settings'
    | '/_app/infra/databases'
    | '/_app/infra/domains'
    | '/_app/infra/relays'
    | '/_app/infra/servers'
    | '/_app/infra/setup'
    | '/_app/infra/tailscale'
    | '/_app/server/$serverId'
    | '/_app/settings/account'
    | '/_app/settings/appearance'
    | '/_app/settings/billing'
    | '/_app/settings/files'
    | '/_app/settings/relays'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/_app/automations/'
    | '/_app/backups/'
    | '/_app/infra/'
    | '/_app/settings/'
    | '/_app/server/$serverId/$'
    | '/_app/server/$serverId/console'
    | '/_app/server/$serverId/files'
    | '/_app/server/$serverId/info'
    | '/_app/server/$serverId/network'
    | '/_app/server/$serverId/startup'
    | '/api/cli/auth/device'
    | '/api/cli/auth/token'
    | '/api/cli/v1/$'
    | '/_app/server/$serverId/'
    | '/_app/server/$serverId/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConsoleRoute: typeof ConsoleRoute
  DiscordRoute: typeof DiscordRoute
  FilesRoute: typeof FilesRoute
  GithubRoute: typeof GithubRoute
  InfoRoute: typeof InfoRoute
  InviteRoute: typeof InviteRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  TwitterRoute: typeof TwitterRoute
  TwoFactorRoute: typeof TwoFactorRoute
  XRoute: typeof XRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiSentryCheckRoute: typeof ApiSentryCheckRoute
  CliAuthorizeRoute: typeof CliAuthorizeRoute
  DownloadsIdRoute: typeof DownloadsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConsoleInstanceIdRoute: typeof ApiConsoleInstanceIdRoute
  ApiCliAuthDeviceRoute: typeof ApiCliAuthDeviceRoute
  ApiCliAuthTokenRoute: typeof ApiCliAuthTokenRoute
  ApiCliV1SplatRoute: typeof ApiCliV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitter': {
      id: '/twitter'
      path: '/twitter'
      fullPath: '/twitter'
      preLoaderRoute: typeof TwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backups': {
      id: '/_app/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AppBackupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infra': {
      id: '/_app/infra'
      path: '/infra'
      fullPath: '/infra'
      preLoaderRoute: typeof AppInfraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations': {
      id: '/_app/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AppOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-check': {
      id: '/api/sentry-check'
      path: '/api/sentry-check'
      fullPath: '/api/sentry-check'
      preLoaderRoute: typeof ApiSentryCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/authorize': {
      id: '/cli/authorize'
      path: '/cli/authorize'
      fullPath: '/cli/authorize'
      preLoaderRoute: typeof CliAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/$id': {
      id: '/downloads/$id'
      path: '/downloads/$id'
      fullPath: '/downloads/$id'
      preLoaderRoute: typeof DownloadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/automations/': {
      id: '/_app/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof AppAutomationsIndexRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/automations/calendar': {
      id: '/_app/automations/calendar'
      path: '/calendar'
      fullPath: '/automations/calendar'
      preLoaderRoute: typeof AppAutomationsCalendarRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/automations/history': {
      id: '/_app/automations/history'
      path: '/history'
      fullPath: '/automations/history'
      preLoaderRoute: typeof AppAutomationsHistoryRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/automations/schedules': {
      id: '/_app/automations/schedules'
      path: '/schedules'
      fullPath: '/automations/schedules'
      preLoaderRoute: typeof AppAutomationsSchedulesRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/automations/sync': {
      id: '/_app/automations/sync'
      path: '/sync'
      fullPath: '/automations/sync'
      preLoaderRoute: typeof AppAutomationsSyncRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/backups/': {
      id: '/_app/backups/'
      path: '/'
      fullPath: '/backups/'
      preLoaderRoute: typeof AppBackupsIndexRouteImport
      parentRoute: typeof AppBackupsRoute
    }
    '/_app/backups/destinations': {
      id: '/_app/backups/destinations'
      path: '/destinations'
      fullPath: '/backups/destinations'
      preLoaderRoute: typeof AppBackupsDestinationsRouteImport
      parentRoute: typeof AppBackupsRoute
    }
    '/_app/backups/runs': {
      id: '/_app/backups/runs'
      path: '/runs'
      fullPath: '/backups/runs'
      preLoaderRoute: typeof AppBackupsRunsRouteImport
      parentRoute: typeof AppBackupsRoute
    }
    '/_app/backups/settings': {
      id: '/_app/backups/settings'
      path: '/settings'
      fullPath: '/backups/settings'
      preLoaderRoute: typeof AppBackupsSettingsRouteImport
      parentRoute: typeof AppBackupsRoute
    }
    '/_app/infra/': {
      id: '/_app/infra/'
      path: '/'
      fullPath: '/infra/'
      preLoaderRoute: typeof AppInfraIndexRouteImport
      parentRoute: typeof AppInfraRoute
    }
    '/_app/infra/databases': {
      id: '/_app/infra/databases'
      path: '/databases'
      fullPath: '/infra/databases'
      preLoaderRoute: typeof AppInfraDatabasesRouteImport
      parentRoute: typeof AppInfraRoute
    }
    '/_app/infra/domains': {
      id: '/_app/infra/domains'
      path: '/domains'
      fullPath: '/infra/domains'
      preLoaderRoute: typeof AppInfraDomainsRouteImport
      parentRoute: typeof AppInfraRoute
    }
    '/_app/infra/relays': {
      id: '/_app/infra/relays'
      path: '/relays'
      fullPath: '/infra/relays'
      preLoaderRoute: typeof AppInfraRelaysRouteImport
      parentRoute: typeof AppInfraRoute
    }
    '/_app/infra/servers': {
      id: '/_app/infra/servers'
      path: '/servers'
      fullPath: '/infra/servers'
      preLoaderRoute: typeof AppInfraServersRouteImport
      parentRoute: typeof AppInfraRoute
    }
    '/_app/infra/setup': {
      id: '/_app/infra/setup'
      path: '/setup'
      fullPath: '/infra/setup'
      preLoaderRoute: typeof AppInfraSetupRouteImport
      parentRoute: typeof AppInfraRoute
    }
    '/_app/infra/tailscale': {
      id: '/_app/infra/tailscale'
      path: '/tailscale'
      fullPath: '/infra/tailscale'
      preLoaderRoute: typeof AppInfraTailscaleRouteImport
      parentRoute: typeof AppInfraRoute
    }
    '/_app/server/$serverId': {
      id: '/_app/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof AppServerServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/files': {
      id: '/_app/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof AppSettingsFilesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/relays': {
      id: '/_app/settings/relays'
      path: '/relays'
      fullPath: '/settings/relays'
      preLoaderRoute: typeof AppSettingsRelaysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/console/$instanceId': {
      id: '/api/console/$instanceId'
      path: '/api/console/$instanceId'
      fullPath: '/api/console/$instanceId'
      preLoaderRoute: typeof ApiConsoleInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/server/$serverId/': {
      id: '/_app/server/$serverId/'
      path: '/'
      fullPath: '/server/$serverId/'
      preLoaderRoute: typeof AppServerServerIdIndexRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/$': {
      id: '/_app/server/$serverId/$'
      path: '/$'
      fullPath: '/server/$serverId/$'
      preLoaderRoute: typeof AppServerServerIdSplatRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/console': {
      id: '/_app/server/$serverId/console'
      path: '/console'
      fullPath: '/server/$serverId/console'
      preLoaderRoute: typeof AppServerServerIdConsoleRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/files': {
      id: '/_app/server/$serverId/files'
      path: '/files'
      fullPath: '/server/$serverId/files'
      preLoaderRoute: typeof AppServerServerIdFilesRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/info': {
      id: '/_app/server/$serverId/info'
      path: '/info'
      fullPath: '/server/$serverId/info'
      preLoaderRoute: typeof AppServerServerIdInfoRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/network': {
      id: '/_app/server/$serverId/network'
      path: '/network'
      fullPath: '/server/$serverId/network'
      preLoaderRoute: typeof AppServerServerIdNetworkRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/startup': {
      id: '/_app/server/$serverId/startup'
      path: '/startup'
      fullPath: '/server/$serverId/startup'
      preLoaderRoute: typeof AppServerServerIdStartupRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/api/cli/auth/device': {
      id: '/api/cli/auth/device'
      path: '/api/cli/auth/device'
      fullPath: '/api/cli/auth/device'
      preLoaderRoute: typeof ApiCliAuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/auth/token': {
      id: '/api/cli/auth/token'
      path: '/api/cli/auth/token'
      fullPath: '/api/cli/auth/token'
      preLoaderRoute: typeof ApiCliAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/v1/$': {
      id: '/api/cli/v1/$'
      path: '/api/cli/v1/$'
      fullPath: '/api/cli/v1/$'
      preLoaderRoute: typeof ApiCliV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/server/$serverId/files/$': {
      id: '/_app/server/$serverId/files/$'
      path: '/$'
      fullPath: '/server/$serverId/files/$'
      preLoaderRoute: typeof AppServerServerIdFilesSplatRouteImport
      parentRoute: typeof AppServerServerIdFilesRoute
    }
  }
}

interface AppAutomationsRouteChildren {
  AppAutomationsCalendarRoute: typeof AppAutomationsCalendarRoute
  AppAutomationsHistoryRoute: typeof AppAutomationsHistoryRoute
  AppAutomationsSchedulesRoute: typeof AppAutomationsSchedulesRoute
  AppAutomationsSyncRoute: typeof AppAutomationsSyncRoute
  AppAutomationsIndexRoute: typeof AppAutomationsIndexRoute
}

const AppAutomationsRouteChildren: AppAutomationsRouteChildren = {
  AppAutomationsCalendarRoute: AppAutomationsCalendarRoute,
  AppAutomationsHistoryRoute: AppAutomationsHistoryRoute,
  AppAutomationsSchedulesRoute: AppAutomationsSchedulesRoute,
  AppAutomationsSyncRoute: AppAutomationsSyncRoute,
  AppAutomationsIndexRoute: AppAutomationsIndexRoute,
}

const AppAutomationsRouteWithChildren = AppAutomationsRoute._addFileChildren(
  AppAutomationsRouteChildren,
)

interface AppBackupsRouteChildren {
  AppBackupsDestinationsRoute: typeof AppBackupsDestinationsRoute
  AppBackupsRunsRoute: typeof AppBackupsRunsRoute
  AppBackupsSettingsRoute: typeof AppBackupsSettingsRoute
  AppBackupsIndexRoute: typeof AppBackupsIndexRoute
}

const AppBackupsRouteChildren: AppBackupsRouteChildren = {
  AppBackupsDestinationsRoute: AppBackupsDestinationsRoute,
  AppBackupsRunsRoute: AppBackupsRunsRoute,
  AppBackupsSettingsRoute: AppBackupsSettingsRoute,
  AppBackupsIndexRoute: AppBackupsIndexRoute,
}

const AppBackupsRouteWithChildren = AppBackupsRoute._addFileChildren(
  AppBackupsRouteChildren,
)

interface AppInfraRouteChildren {
  AppInfraDatabasesRoute: typeof AppInfraDatabasesRoute
  AppInfraDomainsRoute: typeof AppInfraDomainsRoute
  AppInfraRelaysRoute: typeof AppInfraRelaysRoute
  AppInfraServersRoute: typeof AppInfraServersRoute
  AppInfraSetupRoute: typeof AppInfraSetupRoute
  AppInfraTailscaleRoute: typeof AppInfraTailscaleRoute
  AppInfraIndexRoute: typeof AppInfraIndexRoute
}

const AppInfraRouteChildren: AppInfraRouteChildren = {
  AppInfraDatabasesRoute: AppInfraDatabasesRoute,
  AppInfraDomainsRoute: AppInfraDomainsRoute,
  AppInfraRelaysRoute: AppInfraRelaysRoute,
  AppInfraServersRoute: AppInfraServersRoute,
  AppInfraSetupRoute: AppInfraSetupRoute,
  AppInfraTailscaleRoute: AppInfraTailscaleRoute,
  AppInfraIndexRoute: AppInfraIndexRoute,
}

const AppInfraRouteWithChildren = AppInfraRoute._addFileChildren(
  AppInfraRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsFilesRoute: typeof AppSettingsFilesRoute
  AppSettingsRelaysRoute: typeof AppSettingsRelaysRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsFilesRoute: AppSettingsFilesRoute,
  AppSettingsRelaysRoute: AppSettingsRelaysRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppServerServerIdFilesRouteChildren {
  AppServerServerIdFilesSplatRoute: typeof AppServerServerIdFilesSplatRoute
}

const AppServerServerIdFilesRouteChildren: AppServerServerIdFilesRouteChildren =
  {
    AppServerServerIdFilesSplatRoute: AppServerServerIdFilesSplatRoute,
  }

const AppServerServerIdFilesRouteWithChildren =
  AppServerServerIdFilesRoute._addFileChildren(
    AppServerServerIdFilesRouteChildren,
  )

interface AppServerServerIdRouteChildren {
  AppServerServerIdSplatRoute: typeof AppServerServerIdSplatRoute
  AppServerServerIdConsoleRoute: typeof AppServerServerIdConsoleRoute
  AppServerServerIdFilesRoute: typeof AppServerServerIdFilesRouteWithChildren
  AppServerServerIdInfoRoute: typeof AppServerServerIdInfoRoute
  AppServerServerIdNetworkRoute: typeof AppServerServerIdNetworkRoute
  AppServerServerIdStartupRoute: typeof AppServerServerIdStartupRoute
  AppServerServerIdIndexRoute: typeof AppServerServerIdIndexRoute
}

const AppServerServerIdRouteChildren: AppServerServerIdRouteChildren = {
  AppServerServerIdSplatRoute: AppServerServerIdSplatRoute,
  AppServerServerIdConsoleRoute: AppServerServerIdConsoleRoute,
  AppServerServerIdFilesRoute: AppServerServerIdFilesRouteWithChildren,
  AppServerServerIdInfoRoute: AppServerServerIdInfoRoute,
  AppServerServerIdNetworkRoute: AppServerServerIdNetworkRoute,
  AppServerServerIdStartupRoute: AppServerServerIdStartupRoute,
  AppServerServerIdIndexRoute: AppServerServerIdIndexRoute,
}

const AppServerServerIdRouteWithChildren =
  AppServerServerIdRoute._addFileChildren(AppServerServerIdRouteChildren)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccessRoute: typeof AppAccessRoute
  AppActivityRoute: typeof AppActivityRoute
  AppAutomationsRoute: typeof AppAutomationsRouteWithChildren
  AppBackupsRoute: typeof AppBackupsRouteWithChildren
  AppInfraRoute: typeof AppInfraRouteWithChildren
  AppOperationsRoute: typeof AppOperationsRoute
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppServerServerIdRoute: typeof AppServerServerIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccessRoute: AppAccessRoute,
  AppActivityRoute: AppActivityRoute,
  AppAutomationsRoute: AppAutomationsRouteWithChildren,
  AppBackupsRoute: AppBackupsRouteWithChildren,
  AppInfraRoute: AppInfraRouteWithChildren,
  AppOperationsRoute: AppOperationsRoute,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppServerServerIdRoute: AppServerServerIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConsoleRoute: ConsoleRoute,
  DiscordRoute: DiscordRoute,
  FilesRoute: FilesRoute,
  GithubRoute: GithubRoute,
  InfoRoute: InfoRoute,
  InviteRoute: InviteRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  TwitterRoute: TwitterRoute,
  TwoFactorRoute: TwoFactorRoute,
  XRoute: XRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiSentryCheckRoute: ApiSentryCheckRoute,
  CliAuthorizeRoute: CliAuthorizeRoute,
  DownloadsIdRoute: DownloadsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConsoleInstanceIdRoute: ApiConsoleInstanceIdRoute,
  ApiCliAuthDeviceRoute: ApiCliAuthDeviceRoute,
  ApiCliAuthTokenRoute: ApiCliAuthTokenRoute,
  ApiCliV1SplatRoute: ApiCliV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
