// Kiln's schema as the legacy migration scripts left it, captured from a fresh
// install of the last release that used them. Table, index, and constraint
// names are written with the default `kiln_` prefix; the baseline migration
// swaps in the configured prefix. Do not edit: add a new migration instead.

export interface BaselineTable {
  // Table name without the prefix.
  readonly name: string
  readonly create: string
}

export const baselineTables: ReadonlyArray<BaselineTable> = [
  {
    name: "access_grant",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_access_grant\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(36) NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`resource_type\` enum('relay','instance','database') NOT NULL,
  \`resource_id\` varchar(64) NOT NULL,
  \`role\` enum('owner','admin','operator','viewer') DEFAULT NULL,
  \`state\` enum('pending','active','revoked') NOT NULL DEFAULT 'active',
  \`revision\` bigint unsigned NOT NULL DEFAULT '1',
  \`granted_by\` varchar(36) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_access_grant_scope_unique\` (\`user_id\`,\`relay_id\`,\`resource_type\`,\`resource_id\`),
  KEY \`kiln_access_grant_scope_state_idx\` (\`relay_id\`,\`resource_type\`,\`resource_id\`,\`state\`,\`user_id\`),
  KEY \`kiln_access_grant_user_state_idx\` (\`user_id\`,\`state\`,\`relay_id\`)
)`,
  },
  {
    name: "relay",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_relay\` (
  \`id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`name\` varchar(120) NOT NULL,
  \`hostname\` varchar(253) NOT NULL,
  \`port\` smallint unsigned NOT NULL DEFAULT '4100',
  \`use_tls\` tinyint(1) NOT NULL DEFAULT '1',
  \`browser_origin\` varchar(512) NOT NULL,
  \`relay_public_key\` text NOT NULL,
  \`relay_ca_certificate\` text,
  \`client_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`client_public_key\` text NOT NULL,
  \`client_private_key_ciphertext\` text NOT NULL,
  \`client_role\` enum('full_access','read_only','custom') NOT NULL,
  \`client_actions\` json NOT NULL,
  \`issuer_generation\` bigint unsigned NOT NULL DEFAULT '1',
  \`acknowledged_issuer_generation\` bigint unsigned NOT NULL DEFAULT '0',
  \`enabled\` tinyint(1) NOT NULL DEFAULT '1',
  \`last_connected_at\` timestamp(3) NULL DEFAULT NULL,
  \`last_error\` varchar(512) DEFAULT NULL,
  \`managed_ember_count\` int unsigned DEFAULT NULL,
  \`node_arch\` varchar(32) DEFAULT NULL,
  \`node_platform\` varchar(32) DEFAULT NULL,
  \`node_version\` varchar(120) DEFAULT NULL,
  \`created_by\` varchar(36) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_relay_endpoint_unique\` (\`hostname\`,\`port\`)
)`,
  },
  {
    name: "permission_preset",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_permission_preset\` (
  \`id\` char(36) NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`resource_type\` enum('relay','instance','database') NOT NULL,
  \`resource_id\` varchar(64) NOT NULL,
  \`name\` varchar(120) NOT NULL,
  \`revision\` bigint unsigned NOT NULL DEFAULT '1',
  \`created_by\` varchar(36) DEFAULT NULL,
  \`updated_by\` varchar(36) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  KEY \`kiln_permission_preset_scope_idx\` (\`relay_id\`,\`resource_type\`,\`resource_id\`,\`id\`),
  CONSTRAINT \`kiln_permission_preset_relay_fk\` FOREIGN KEY (\`relay_id\`) REFERENCES \`kiln_relay\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "access_preset",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_access_preset\` (
  \`id\` char(36) NOT NULL,
  \`access_id\` char(36) NOT NULL,
  \`preset_id\` char(36) DEFAULT NULL,
  \`builtin_key\` varchar(120) DEFAULT NULL,
  \`granted_by\` varchar(36) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_access_preset_custom_unique\` (\`access_id\`,\`preset_id\`),
  UNIQUE KEY \`kiln_access_preset_builtin_unique\` (\`access_id\`,\`builtin_key\`),
  KEY \`kiln_access_preset_reverse_idx\` (\`preset_id\`,\`access_id\`),
  CONSTRAINT \`kiln_access_preset_access_fk\` FOREIGN KEY (\`access_id\`) REFERENCES \`kiln_access_grant\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`kiln_access_preset_preset_fk\` FOREIGN KEY (\`preset_id\`) REFERENCES \`kiln_permission_preset\` (\`id\`) ON DELETE RESTRICT,
  CONSTRAINT \`kiln_access_preset_reference_chk\` CHECK (((\`preset_id\` is null) <> (\`builtin_key\` is null)))
)`,
  },
  {
    name: "access_selection",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_access_selection\` (
  \`access_id\` char(36) NOT NULL,
  \`selection_kind\` enum('permission','collection') NOT NULL,
  \`selection_key\` varchar(120) NOT NULL,
  PRIMARY KEY (\`access_id\`,\`selection_kind\`,\`selection_key\`),
  CONSTRAINT \`kiln_access_selection_access_fk\` FOREIGN KEY (\`access_id\`) REFERENCES \`kiln_access_grant\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "account",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_account\` (
  \`id\` varchar(36) NOT NULL,
  \`accountId\` text NOT NULL,
  \`providerId\` text NOT NULL,
  \`userId\` varchar(36) NOT NULL,
  \`accessToken\` text,
  \`refreshToken\` text,
  \`idToken\` text,
  \`accessTokenExpiresAt\` timestamp(3) NULL DEFAULT NULL,
  \`refreshTokenExpiresAt\` timestamp(3) NULL DEFAULT NULL,
  \`scope\` text,
  \`password\` text,
  \`createdAt\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updatedAt\` timestamp(3) NOT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`kiln_account_userId_idx\` (\`userId\`)
)`,
  },
  {
    name: "user",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_user\` (
  \`id\` varchar(36) NOT NULL,
  \`name\` varchar(255) NOT NULL,
  \`email\` varchar(255) NOT NULL,
  \`emailVerified\` tinyint(1) NOT NULL,
  \`image\` text,
  \`createdAt\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updatedAt\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`role\` text,
  \`banned\` tinyint(1) DEFAULT NULL,
  \`banReason\` text,
  \`banExpires\` timestamp(3) NULL DEFAULT NULL,
  \`twoFactorEnabled\` tinyint(1) DEFAULT NULL,
  \`status\` varchar(16) NOT NULL DEFAULT 'enabled',
  \`statusChangedAt\` timestamp(3) NULL DEFAULT NULL,
  \`statusChangedBy\` varchar(36) DEFAULT NULL,
  \`statusReason\` text,
  \`statusExpiresAt\` timestamp(3) NULL DEFAULT NULL,
  \`emailVerifiedAt\` timestamp(3) NULL DEFAULT NULL,
  \`manuallyVerifiedAt\` timestamp(3) NULL DEFAULT NULL,
  \`manuallyVerifiedBy\` varchar(36) DEFAULT NULL,
  \`legacyVerificationRecordedAt\` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`email\` (\`email\`)
)`,
  },
  {
    name: "account_claim",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_account_claim\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(36) NOT NULL,
  \`token_hash\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`proof_method\` enum('email','manual') NOT NULL,
  \`created_by\` varchar(36) DEFAULT NULL,
  \`expires_at\` timestamp(3) NOT NULL,
  \`consumed_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_account_claim_token_unique\` (\`token_hash\`),
  KEY \`kiln_account_claim_user_idx\` (\`user_id\`,\`expires_at\`),
  CONSTRAINT \`kiln_account_claim_user_fk\` FOREIGN KEY (\`user_id\`) REFERENCES \`kiln_user\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "auth_audit",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_auth_audit\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`user_id\` varchar(36) DEFAULT NULL,
  \`event\` varchar(120) NOT NULL,
  \`ip_address\` varchar(64) DEFAULT NULL,
  \`user_agent\` varchar(512) DEFAULT NULL,
  \`metadata\` json DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  KEY \`kiln_auth_audit_user_created_idx\` (\`user_id\`,\`created_at\`)
)`,
  },
  {
    name: "authorization_delivery",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_authorization_delivery\` (
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`subject_id\` varchar(36) NOT NULL,
  \`scope_kind\` enum('instance','subject_relay','login_session') NOT NULL,
  \`scope_id\` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`desired_revision\` bigint unsigned NOT NULL,
  \`acknowledged_revision\` bigint unsigned NOT NULL DEFAULT '0',
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`relay_id\`,\`subject_id\`,\`scope_kind\`,\`scope_id\`),
  KEY \`kiln_authorization_delivery_pending_idx\` (\`relay_id\`,\`acknowledged_revision\`,\`desired_revision\`,\`updated_at\`),
  CONSTRAINT \`kiln_authorization_delivery_relay_fk\` FOREIGN KEY (\`relay_id\`) REFERENCES \`kiln_relay\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "authorization_subject",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_authorization_subject\` (
  \`user_id\` varchar(36) NOT NULL,
  \`revision\` bigint unsigned NOT NULL DEFAULT '0',
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`user_id\`)
)`,
  },
  {
    name: "backup_storage",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_storage\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`owner_user_id\` varchar(36) DEFAULT NULL,
  \`name\` varchar(120) NOT NULL,
  \`endpoint\` varchar(2048) NOT NULL,
  \`region\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`bucket\` varchar(255) NOT NULL,
  \`object_prefix\` varchar(512) NOT NULL DEFAULT '',
  \`force_path_style\` tinyint(1) NOT NULL DEFAULT '0',
  \`allow_private_network\` tinyint(1) NOT NULL DEFAULT '0',
  \`access_key_id_ciphertext\` text NOT NULL,
  \`secret_access_key_ciphertext\` text NOT NULL,
  \`enabled\` tinyint(1) NOT NULL DEFAULT '1',
  \`deleting\` tinyint(1) NOT NULL DEFAULT '0',
  \`last_verified_at\` timestamp(3) NULL DEFAULT NULL,
  \`last_error\` varchar(512) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_backup_storage_owner_name_unique\` (\`owner_user_id\`,\`name\`),
  KEY \`kiln_backup_storage_owner_enabled_idx\` (\`owner_user_id\`,\`enabled\`,\`name\`)
)`,
  },
  {
    name: "backup_repository",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_repository\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`target_kind\` enum('instance','database','platform') NOT NULL,
  \`target_id\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`storage_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`storage_key\` varchar(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'local',
  \`object_prefix\` varchar(1024) DEFAULT NULL,
  \`password_ciphertext\` text NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_backup_repository_target_storage_unique\` (\`relay_id\`,\`target_kind\`,\`target_id\`,\`storage_key\`),
  KEY \`kiln_backup_repository_storage_idx\` (\`storage_id\`),
  CONSTRAINT \`kiln_backup_repository_storage_fk\` FOREIGN KEY (\`storage_id\`) REFERENCES \`kiln_backup_storage\` (\`id\`) ON DELETE RESTRICT,
  CONSTRAINT \`kiln_backup_repository_storage_key_chk\` CHECK ((\`storage_key\` = ifnull(\`storage_id\`,_utf8mb4'local')))
)`,
  },
  {
    name: "backup",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`target_kind\` enum('instance','database','platform') NOT NULL,
  \`target_id\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`storage_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`artifact_kind\` enum('archive','database_dump','platform_bundle','restic_snapshot') NOT NULL,
  \`backup_mode\` enum('full','incremental') NOT NULL DEFAULT 'full',
  \`reason\` enum('manual','pre_restore','final_delete','scheduled') NOT NULL,
  \`status\` enum('queued','running','available','failed','deleting','deleted') NOT NULL,
  \`name\` varchar(120) NOT NULL,
  \`filename\` varchar(255) DEFAULT NULL,
  \`object_key\` varchar(1024) DEFAULT NULL,
  \`bytes\` bigint unsigned DEFAULT NULL,
  \`checksum_sha256\` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`restic_snapshot_id\` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`repository_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`warnings\` json NOT NULL,
  \`created_by\` varchar(36) DEFAULT NULL,
  \`started_at\` timestamp(3) NULL DEFAULT NULL,
  \`completed_at\` timestamp(3) NULL DEFAULT NULL,
  \`deleted_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  KEY \`kiln_backup_target_created_idx\` (\`relay_id\`,\`target_kind\`,\`target_id\`,\`created_at\`),
  KEY \`kiln_backup_created_idx\` (\`created_at\`,\`id\`),
  KEY \`kiln_backup_status_updated_idx\` (\`status\`,\`updated_at\`),
  KEY \`kiln_backup_storage_idx\` (\`storage_id\`),
  KEY \`kiln_backup_repository_idx\` (\`repository_id\`),
  CONSTRAINT \`kiln_backup_repository_fk\` FOREIGN KEY (\`repository_id\`) REFERENCES \`kiln_backup_repository\` (\`id\`) ON DELETE RESTRICT,
  CONSTRAINT \`kiln_backup_storage_fk\` FOREIGN KEY (\`storage_id\`) REFERENCES \`kiln_backup_storage\` (\`id\`) ON DELETE RESTRICT
)`,
  },
  {
    name: "backup_artifact",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_artifact\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`backup_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`destination_key\` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`storage_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`status\` enum('queued','running','available','failed','deleting','deleted') NOT NULL,
  \`filename\` varchar(255) DEFAULT NULL,
  \`object_key\` varchar(1024) DEFAULT NULL,
  \`bytes\` bigint unsigned DEFAULT NULL,
  \`checksum_sha256\` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`error\` text,
  \`completed_at\` timestamp(3) NULL DEFAULT NULL,
  \`deleted_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_backup_artifact_destination_unique\` (\`backup_id\`,\`destination_key\`),
  KEY \`kiln_backup_artifact_status_idx\` (\`status\`,\`updated_at\`),
  KEY \`kiln_backup_artifact_storage_idx\` (\`storage_id\`),
  CONSTRAINT \`kiln_backup_artifact_backup_fk\` FOREIGN KEY (\`backup_id\`) REFERENCES \`kiln_backup\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`kiln_backup_artifact_storage_fk\` FOREIGN KEY (\`storage_id\`) REFERENCES \`kiln_backup_storage\` (\`id\`) ON DELETE RESTRICT
)`,
  },
  {
    name: "backup_copy_task",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_copy_task\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`backup_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`source_artifact_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`destination_artifact_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`status\` enum('queued','running','succeeded','failed') NOT NULL,
  \`requested_by\` varchar(36) NOT NULL,
  \`error\` text,
  \`started_at\` timestamp(3) NULL DEFAULT NULL,
  \`finished_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_backup_copy_task_destination_unique\` (\`destination_artifact_id\`),
  KEY \`kiln_backup_copy_task_status_updated_idx\` (\`status\`,\`updated_at\`),
  KEY \`kiln_backup_copy_task_backup_fk\` (\`backup_id\`),
  KEY \`kiln_backup_copy_task_source_artifact_fk\` (\`source_artifact_id\`),
  CONSTRAINT \`kiln_backup_copy_task_backup_fk\` FOREIGN KEY (\`backup_id\`) REFERENCES \`kiln_backup\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`kiln_backup_copy_task_destination_artifact_fk\` FOREIGN KEY (\`destination_artifact_id\`) REFERENCES \`kiln_backup_artifact\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`kiln_backup_copy_task_source_artifact_fk\` FOREIGN KEY (\`source_artifact_id\`) REFERENCES \`kiln_backup_artifact\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "backup_download_share",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_download_share\` (
  \`token_hash\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`download_url_ciphertext\` text NOT NULL,
  \`backup_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`backup_name\` varchar(120) NOT NULL,
  \`filename\` varchar(255) NOT NULL,
  \`bytes\` bigint unsigned DEFAULT NULL,
  \`checksum_sha256\` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`artifact_kind\` enum('archive','database_dump','platform_bundle','restic_snapshot') NOT NULL,
  \`target_kind\` enum('instance','database','platform') NOT NULL,
  \`target_id\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`source_name\` varchar(120) NOT NULL,
  \`shared_by\` varchar(120) NOT NULL,
  \`backup_created_at\` timestamp(3) NOT NULL,
  \`expires_at\` timestamp(3) NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`token_hash\`),
  KEY \`kiln_backup_download_share_expiry_idx\` (\`expires_at\`)
)`,
  },
  {
    name: "backup_final_database_delete",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_final_database_delete\` (
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`target_id\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`backup_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`requested_by\` varchar(36) NOT NULL,
  \`status\` enum('backing_up','deleting','failed','completed') NOT NULL,
  \`error\` text,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`relay_id\`,\`target_id\`),
  UNIQUE KEY \`kiln_backup_final_database_delete_backup_unique\` (\`backup_id\`),
  KEY \`kiln_backup_final_database_delete_status_idx\` (\`status\`,\`updated_at\`),
  CONSTRAINT \`kiln_backup_final_database_delete_backup_fk\` FOREIGN KEY (\`backup_id\`) REFERENCES \`kiln_backup\` (\`id\`) ON DELETE RESTRICT
)`,
  },
  {
    name: "backup_final_delete",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_final_delete\` (
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`target_id\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`backup_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`requested_by\` varchar(36) NOT NULL,
  \`status\` enum('backing_up','deleting','failed','completed') NOT NULL,
  \`error\` text,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`relay_id\`,\`target_id\`),
  UNIQUE KEY \`kiln_backup_final_delete_backup_unique\` (\`backup_id\`),
  KEY \`kiln_backup_final_delete_status_idx\` (\`status\`,\`updated_at\`),
  CONSTRAINT \`kiln_backup_final_delete_backup_fk\` FOREIGN KEY (\`backup_id\`) REFERENCES \`kiln_backup\` (\`id\`) ON DELETE RESTRICT
)`,
  },
  {
    name: "backup_policy",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_policy\` (
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`target_kind\` enum('instance','database','platform') NOT NULL,
  \`target_id\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`storage_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`exclude_patterns\` json NOT NULL,
  \`quantity_limit\` int unsigned DEFAULT NULL,
  \`size_limit_bytes\` bigint unsigned DEFAULT NULL,
  \`admin_quantity_limit\` int unsigned DEFAULT NULL,
  \`admin_size_limit_bytes\` bigint unsigned DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`relay_id\`,\`target_kind\`,\`target_id\`),
  KEY \`kiln_backup_policy_storage_idx\` (\`storage_id\`),
  CONSTRAINT \`kiln_backup_policy_storage_fk\` FOREIGN KEY (\`storage_id\`) REFERENCES \`kiln_backup_storage\` (\`id\`) ON DELETE SET NULL
)`,
  },
  {
    name: "backup_task",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_backup_task\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`backup_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`task_kind\` enum('create','restore','delete','export') NOT NULL,
  \`status\` enum('queued','running','succeeded','failed','cancelled') NOT NULL,
  \`bytes_completed\` bigint unsigned NOT NULL DEFAULT '0',
  \`bytes_total\` bigint unsigned DEFAULT NULL,
  \`phase\` enum('preparing','collecting','archiving','dumping','uploading','finalizing') DEFAULT NULL,
  \`current_artifact_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`current_path\` varchar(2048) DEFAULT NULL,
  \`reserved_bytes\` bigint unsigned DEFAULT NULL,
  \`relay_updated_at_ms\` bigint unsigned DEFAULT NULL,
  \`depends_on_task_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`error\` text,
  \`requested_by\` varchar(36) DEFAULT NULL,
  \`started_at\` timestamp(3) NULL DEFAULT NULL,
  \`finished_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  KEY \`kiln_backup_task_backup_created_id_idx\` (\`backup_id\`,\`created_at\`,\`id\`),
  KEY \`kiln_backup_task_status_updated_idx\` (\`status\`,\`updated_at\`),
  KEY \`kiln_backup_task_dependency_idx\` (\`depends_on_task_id\`),
  CONSTRAINT \`kiln_backup_task_backup_fk\` FOREIGN KEY (\`backup_id\`) REFERENCES \`kiln_backup\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "brick_catalog",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_brick_catalog\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`owner_user_id\` varchar(36) NOT NULL,
  \`source_hash\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`source\` varchar(2048) NOT NULL,
  \`snapshot\` json NOT NULL,
  \`snapshot_sha256\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`revision_sha\` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`revision_url\` varchar(2048) DEFAULT NULL,
  \`visibility\` enum('personal','community') NOT NULL DEFAULT 'personal',
  \`published_by\` varchar(36) DEFAULT NULL,
  \`published_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_brick_catalog_owner_source_unique\` (\`owner_user_id\`,\`source_hash\`),
  KEY \`kiln_brick_catalog_visibility_updated_idx\` (\`visibility\`,\`updated_at\`),
  KEY \`kiln_brick_catalog_owner_updated_idx\` (\`owner_user_id\`,\`updated_at\`)
)`,
  },
  {
    name: "cli_credential",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_cli_credential\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(36) NOT NULL,
  \`name\` varchar(120) NOT NULL,
  \`token_hash\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`access_mode\` enum('full_access','read_only') NOT NULL,
  \`expires_at\` timestamp(3) NULL DEFAULT NULL,
  \`last_used_at\` timestamp(3) NULL DEFAULT NULL,
  \`revoked_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_cli_credential_token_unique\` (\`token_hash\`),
  KEY \`kiln_cli_credential_user_created_idx\` (\`user_id\`,\`created_at\`),
  KEY \`kiln_cli_credential_expiry_idx\` (\`expires_at\`,\`revoked_at\`)
)`,
  },
  {
    name: "cli_device",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_cli_device\` (
  \`id\` char(36) NOT NULL,
  \`device_code_hash\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`user_code_hash\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`client_name\` varchar(120) NOT NULL,
  \`status\` enum('pending','approved','denied') NOT NULL DEFAULT 'pending',
  \`user_id\` varchar(36) DEFAULT NULL,
  \`credential_id\` char(36) DEFAULT NULL,
  \`token_ciphertext\` text,
  \`access_mode\` enum('full_access','read_only') DEFAULT NULL,
  \`credential_expires_at\` timestamp(3) NULL DEFAULT NULL,
  \`last_polled_at\` timestamp(3) NULL DEFAULT NULL,
  \`authorized_at\` timestamp(3) NULL DEFAULT NULL,
  \`expires_at\` timestamp(3) NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_cli_device_code_unique\` (\`device_code_hash\`),
  UNIQUE KEY \`kiln_cli_user_code_unique\` (\`user_code_hash\`),
  KEY \`kiln_cli_device_expiry_idx\` (\`expires_at\`,\`status\`),
  KEY \`kiln_cli_device_credential_fk\` (\`credential_id\`),
  CONSTRAINT \`kiln_cli_device_credential_fk\` FOREIGN KEY (\`credential_id\`) REFERENCES \`kiln_cli_credential\` (\`id\`) ON DELETE SET NULL
)`,
  },
  {
    name: "custom_brick",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_custom_brick\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`owner_user_id\` varchar(36) NOT NULL,
  \`source_hash\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`source\` varchar(2048) NOT NULL,
  \`recipe\` json NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_custom_brick_owner_source_unique\` (\`owner_user_id\`,\`source_hash\`),
  KEY \`kiln_custom_brick_owner_updated_idx\` (\`owner_user_id\`,\`updated_at\`)
)`,
  },
  {
    name: "data_migration",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_data_migration\` (
  \`id\` varchar(120) NOT NULL,
  \`completed_at\` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (\`id\`)
)`,
  },
  {
    name: "database",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_database\` (
  \`database_id\` char(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`name\` varchar(120) NOT NULL,
  \`engine\` enum('mysql','mariadb','postgres','redis','valkey') NOT NULL,
  \`database_name\` varchar(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`username\` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`password_ciphertext\` text NOT NULL,
  \`created_by\` varchar(36) NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`database_id\`),
  UNIQUE KEY \`kiln_database_relay_name_unique\` (\`relay_id\`,\`name\`),
  KEY \`kiln_database_relay_idx\` (\`relay_id\`,\`created_at\`),
  KEY \`kiln_database_owner_scope_idx\` (\`created_by\`,\`relay_id\`,\`database_id\`),
  CONSTRAINT \`kiln_database_relay_fk\` FOREIGN KEY (\`relay_id\`) REFERENCES \`kiln_relay\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "domain_integration",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_domain_integration\` (
  \`id\` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`provider\` enum('cloudflare') NOT NULL,
  \`domain\` varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`zone_id\` char(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`zone_name\` varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`api_token_ciphertext\` text NOT NULL,
  \`blacklist_patterns\` json NOT NULL,
  \`enabled\` tinyint(1) NOT NULL DEFAULT '1',
  \`last_verified_at\` timestamp(3) NULL DEFAULT NULL,
  \`last_error\` varchar(512) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`)
)`,
  },
  {
    name: "instance",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_instance\` (
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`instance_id\` char(40) NOT NULL,
  \`display_name\` varchar(32) DEFAULT NULL,
  \`source_name\` varchar(255) DEFAULT NULL,
  \`owner_id\` varchar(36) DEFAULT NULL,
  \`provisioning_reserved_until\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`relay_id\`,\`instance_id\`),
  UNIQUE KEY \`kiln_instance_relay_name_unique\` (\`relay_id\`,\`display_name\`),
  KEY \`kiln_instance_owner_scope_idx\` (\`owner_id\`,\`relay_id\`,\`instance_id\`),
  CONSTRAINT \`kiln_instance_relay_fk\` FOREIGN KEY (\`relay_id\`) REFERENCES \`kiln_relay\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "file_activity",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_file_activity\` (
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`instance_id\` char(40) NOT NULL,
  \`path_hash\` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`path\` varchar(2048) NOT NULL,
  \`pinned\` tinyint(1) NOT NULL DEFAULT '0',
  \`last_viewed_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`last_edited_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`relay_id\`,\`instance_id\`,\`path_hash\`),
  KEY \`kiln_file_activity_recent_idx\` (\`relay_id\`,\`instance_id\`,\`pinned\`,\`last_viewed_at\`),
  CONSTRAINT \`kiln_file_activity_instance_fk\` FOREIGN KEY (\`relay_id\`, \`instance_id\`) REFERENCES \`kiln_instance\` (\`relay_id\`, \`instance_id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "instance_domain",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_instance_domain\` (
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`instance_id\` char(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`integration_id\` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`vanity_label\` varchar(63) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`domain\` varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`public_host\` varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`public_port\` smallint unsigned NOT NULL,
  \`supports_srv\` tinyint(1) NOT NULL DEFAULT '0',
  \`srv_service\` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`srv_protocol\` enum('tcp','udp') DEFAULT NULL,
  \`address_record_id\` char(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`address_record_type\` enum('A','AAAA','CNAME') DEFAULT NULL,
  \`srv_record_id\` char(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`status\` enum('pending','active','error') NOT NULL DEFAULT 'pending',
  \`last_error\` varchar(512) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`relay_id\`,\`instance_id\`),
  UNIQUE KEY \`kiln_instance_domain_vanity_unique\` (\`domain\`,\`vanity_label\`),
  KEY \`kiln_instance_domain_status_idx\` (\`status\`,\`updated_at\`)
)`,
  },
  {
    name: "instance_post_provision",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_instance_post_provision\` (
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`instance_id\` char(40) NOT NULL,
  \`attempts\` int unsigned NOT NULL DEFAULT '0',
  \`next_attempt_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`last_error\` varchar(512) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`relay_id\`,\`instance_id\`),
  KEY \`kiln_instance_post_provision_due_idx\` (\`next_attempt_at\`,\`updated_at\`),
  CONSTRAINT \`kiln_instance_post_provision_instance_fk\` FOREIGN KEY (\`relay_id\`, \`instance_id\`) REFERENCES \`kiln_instance\` (\`relay_id\`, \`instance_id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "invitation",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_invitation\` (
  \`id\` char(36) NOT NULL,
  \`token_hash\` char(64) NOT NULL,
  \`email\` varchar(320) NOT NULL,
  \`access_id\` char(36) DEFAULT NULL,
  \`user_id\` varchar(36) DEFAULT NULL,
  \`accepted_by\` varchar(36) DEFAULT NULL,
  \`acceptance_method\` enum('self','admin','legacy') DEFAULT NULL,
  \`declined_at\` timestamp(3) NULL DEFAULT NULL,
  \`cancelled_at\` timestamp(3) NULL DEFAULT NULL,
  \`cancelled_by\` varchar(36) DEFAULT NULL,
  \`delivery_status\` enum('pending','sent','failed','not_required','legacy') NOT NULL DEFAULT 'pending',
  \`delivery_attempts\` int unsigned NOT NULL DEFAULT '0',
  \`delivery_last_error\` varchar(512) DEFAULT NULL,
  \`delivery_next_attempt_at\` timestamp(3) NULL DEFAULT NULL,
  \`sent_at\` timestamp(3) NULL DEFAULT NULL,
  \`access_type\` enum('scoped','platform_admin','relay_creator') NOT NULL DEFAULT 'scoped',
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`instance_id\` varchar(64) DEFAULT NULL,
  \`database_id\` char(40) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`role\` enum('owner','admin','operator','viewer') DEFAULT NULL,
  \`invited_by\` varchar(36) NOT NULL,
  \`expires_at\` timestamp(3) NOT NULL,
  \`accepted_at\` timestamp(3) NULL DEFAULT NULL,
  \`revoked_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_invitation_token_unique\` (\`token_hash\`),
  KEY \`kiln_invitation_user_access_idx\` (\`user_id\`,\`access_id\`,\`expires_at\`),
  KEY \`kiln_invitation_delivery_idx\` (\`delivery_status\`,\`delivery_next_attempt_at\`),
  KEY \`kiln_invitation_access_expiry_idx\` (\`access_id\`,\`expires_at\`),
  KEY \`kiln_invitation_email_pending_idx\` (\`email\`,\`expires_at\`),
  KEY \`kiln_invitation_relay_idx\` (\`relay_id\`,\`created_at\`)
)`,
  },
  {
    name: "passkey",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_passkey\` (
  \`id\` varchar(36) NOT NULL,
  \`name\` text,
  \`publicKey\` text NOT NULL,
  \`userId\` varchar(36) NOT NULL,
  \`credentialID\` varchar(255) NOT NULL,
  \`counter\` int NOT NULL,
  \`deviceType\` text NOT NULL,
  \`backedUp\` tinyint(1) NOT NULL,
  \`transports\` text,
  \`createdAt\` timestamp(3) NULL DEFAULT NULL,
  \`aaguid\` text,
  PRIMARY KEY (\`id\`),
  KEY \`kiln_passkey_userId_idx\` (\`userId\`),
  KEY \`kiln_passkey_credentialID_idx\` (\`credentialID\`)
)`,
  },
  {
    name: "preset_selection",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_preset_selection\` (
  \`preset_id\` char(36) NOT NULL,
  \`selection_kind\` enum('permission','collection') NOT NULL,
  \`selection_key\` varchar(120) NOT NULL,
  PRIMARY KEY (\`preset_id\`,\`selection_kind\`,\`selection_key\`),
  CONSTRAINT \`kiln_preset_selection_preset_fk\` FOREIGN KEY (\`preset_id\`) REFERENCES \`kiln_permission_preset\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "rateLimit",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_rateLimit\` (
  \`id\` varchar(36) NOT NULL,
  \`key\` varchar(255) NOT NULL,
  \`count\` int NOT NULL,
  \`lastRequest\` bigint NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`key\` (\`key\`)
)`,
  },
  {
    name: "schedule",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_schedule\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`name\` varchar(120) NOT NULL,
  \`cron_expression\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`timezone\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`enabled\` tinyint(1) NOT NULL DEFAULT '1',
  \`revision\` int unsigned NOT NULL DEFAULT '1',
  \`created_by\` varchar(36) NOT NULL,
  \`deleted_at\` timestamp(3) NULL DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  KEY \`kiln_schedule_created_by_idx\` (\`created_by\`,\`updated_at\`),
  KEY \`kiln_schedule_enabled_idx\` (\`enabled\`,\`updated_at\`)
)`,
  },
  {
    name: "schedule_action",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_schedule_action\` (
  \`id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`schedule_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`position\` smallint unsigned NOT NULL,
  \`action_type\` enum('console_command','backup','power','wait') NOT NULL,
  \`action_config\` json NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_schedule_action_position_unique\` (\`schedule_id\`,\`position\`),
  CONSTRAINT \`kiln_schedule_action_schedule_fk\` FOREIGN KEY (\`schedule_id\`) REFERENCES \`kiln_schedule\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "schedule_deployment",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_schedule_deployment\` (
  \`schedule_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`desired_revision\` int unsigned NOT NULL,
  \`acknowledged_revision\` int unsigned DEFAULT NULL,
  \`status\` enum('pending','applied','error') NOT NULL DEFAULT 'pending',
  \`next_run_at\` timestamp(3) NULL DEFAULT NULL,
  \`last_error\` varchar(2000) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`schedule_id\`,\`relay_id\`),
  KEY \`kiln_schedule_deployment_status_idx\` (\`status\`,\`updated_at\`),
  KEY \`kiln_schedule_deployment_relay_fk\` (\`relay_id\`),
  CONSTRAINT \`kiln_schedule_deployment_relay_fk\` FOREIGN KEY (\`relay_id\`) REFERENCES \`kiln_relay\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`kiln_schedule_deployment_schedule_fk\` FOREIGN KEY (\`schedule_id\`) REFERENCES \`kiln_schedule\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "schedule_run",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_schedule_run\` (
  \`id\` char(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`schedule_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`scheduled_at\` timestamp(3) NOT NULL,
  \`status\` enum('running','succeeded','partial','failed','noop','interrupted','missed') NOT NULL,
  \`run_json\` json NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  KEY \`kiln_schedule_run_schedule_idx\` (\`schedule_id\`,\`scheduled_at\` DESC),
  KEY \`kiln_schedule_run_relay_idx\` (\`relay_id\`,\`scheduled_at\` DESC),
  CONSTRAINT \`kiln_schedule_run_relay_fk\` FOREIGN KEY (\`relay_id\`) REFERENCES \`kiln_relay\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "schedule_target",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_schedule_target\` (
  \`schedule_id\` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`target_kind\` enum('instance','database','relay') NOT NULL,
  \`target_id\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`target_name\` varchar(120) NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`schedule_id\`,\`relay_id\`,\`target_kind\`,\`target_id\`),
  KEY \`kiln_schedule_target_relay_idx\` (\`relay_id\`,\`target_kind\`,\`target_id\`),
  CONSTRAINT \`kiln_schedule_target_relay_fk\` FOREIGN KEY (\`relay_id\`) REFERENCES \`kiln_relay\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`kiln_schedule_target_schedule_fk\` FOREIGN KEY (\`schedule_id\`) REFERENCES \`kiln_schedule\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "session",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_session\` (
  \`id\` varchar(36) NOT NULL,
  \`expiresAt\` timestamp(3) NOT NULL,
  \`token\` varchar(255) NOT NULL,
  \`createdAt\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updatedAt\` timestamp(3) NOT NULL,
  \`ipAddress\` text,
  \`userAgent\` text,
  \`userId\` varchar(36) NOT NULL,
  \`impersonatedBy\` text,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`token\` (\`token\`),
  KEY \`kiln_session_userId_idx\` (\`userId\`)
)`,
  },
  {
    name: "setting",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_setting\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(36) DEFAULT NULL,
  \`setting_key\` varchar(191) NOT NULL,
  \`setting_value\` json NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_setting_scope_unique\` (\`user_id\`,\`setting_key\`)
)`,
  },
  {
    name: "tailscale_network",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_tailscale_network\` (
  \`id\` char(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`name\` varchar(32) NOT NULL,
  \`domain\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`oauth_client_id\` varchar(120) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  \`oauth_client_secret_ciphertext\` text,
  \`oauth_scopes\` json DEFAULT NULL,
  \`oauth_tags\` json DEFAULT NULL,
  \`oauth_last_synced_at\` timestamp(3) NULL DEFAULT NULL,
  \`oauth_last_error\` varchar(512) DEFAULT NULL,
  \`deletion_requested_at\` timestamp(3) NULL DEFAULT NULL,
  \`deletion_requested_by\` varchar(36) DEFAULT NULL,
  \`cleanup_attempts\` int unsigned NOT NULL DEFAULT '0',
  \`cleanup_next_attempt_at\` timestamp(3) NULL DEFAULT NULL,
  \`cleanup_last_error\` varchar(512) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`kiln_tailscale_network_domain_unique\` (\`domain\`)
)`,
  },
  {
    name: "tailscale_network_deployment",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_tailscale_network_deployment\` (
  \`network_id\` char(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`relay_id\` char(43) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  \`deployment\` json NOT NULL,
  \`cleanup_attempts\` int unsigned NOT NULL DEFAULT '0',
  \`cleanup_next_attempt_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`cleanup_last_error\` varchar(512) DEFAULT NULL,
  \`observed_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`network_id\`,\`relay_id\`),
  KEY \`kiln_tailscale_network_deployment_cleanup_due_idx\` (\`cleanup_next_attempt_at\`,\`updated_at\`),
  CONSTRAINT \`kiln_tailscale_network_deployment_network_fk\` FOREIGN KEY (\`network_id\`) REFERENCES \`kiln_tailscale_network\` (\`id\`) ON DELETE CASCADE
)`,
  },
  {
    name: "twoFactor",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_twoFactor\` (
  \`id\` varchar(36) NOT NULL,
  \`secret\` varchar(255) NOT NULL,
  \`backupCodes\` text NOT NULL,
  \`userId\` varchar(36) NOT NULL,
  \`verified\` tinyint(1) DEFAULT NULL,
  \`failedVerificationCount\` int DEFAULT NULL,
  \`lockedUntil\` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`kiln_twoFactor_secret_idx\` (\`secret\`),
  KEY \`kiln_twoFactor_userId_idx\` (\`userId\`)
)`,
  },
  {
    name: "verification",
    create: `CREATE TABLE IF NOT EXISTS \`kiln_verification\` (
  \`id\` varchar(36) NOT NULL,
  \`identifier\` varchar(255) NOT NULL,
  \`value\` text NOT NULL,
  \`expiresAt\` timestamp(3) NOT NULL,
  \`createdAt\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updatedAt\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  KEY \`kiln_verification_identifier_idx\` (\`identifier\`)
)`,
  },
]
